import chalk from 'chalk';
import { writeFileSync, chmodSync } from 'fs';
import { getServiceConfig } from '../config/loader.js';
import { exec, isRoot } from '../utils/shell.js';
import { ensureDir, exists, joinPath } from '../utils/files.js';
import { initBareRepo } from '../utils/git.js';

interface InitOptions {
  users?: string;
}

/**
 * Generate post-receive hook content
 */
function generateHook(serviceName: string, config: ReturnType<typeof getServiceConfig>): string {
  const { server, packages, mainPackage, processName, processManager = 'pm2', pm2Home } = config;
  
  // Generate hook based on process manager type
  if (processManager === 'systemd') {
    return generateSystemdHook(serviceName, config);
  }
  
  // Default: PM2 hook
  const pm2Env = pm2Home ? `PM2_HOME=${pm2Home} ` : '';
  
  return `#!/bin/bash
# Post-receive hook for ${serviceName}
# Generated by git-deploy-cli
# Process Manager: pm2

set -e

SERVICE="${serviceName}"
TARGET_DIR="${server.targetDir}"
LOG_FILE="/var/log/deploy-${serviceName}.log"
PROCESS_NAME="${processName}"
PACKAGES=(${packages.map(p => `"${p}"`).join(' ')})
MAIN_PKG="${mainPackage}"
USER="${server.user || 'root'}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | sudo tee -a "$LOG_FILE"
}

log "=== Deployment started ==="

while read oldrev newrev refname; do
    BRANCH=$(echo "$refname" | sed 's|refs/heads/||')
    log "Received push to branch: $BRANCH"
    
    if [ "$BRANCH" != "main" ] && [ "$BRANCH" != "master" ]; then
        log "Ignoring non-main branch"
        continue
    fi

    # Extract packages using git archive
    for pkg in "\${PACKAGES[@]}"; do
        log "Extracting $pkg..."
        git archive "$BRANCH" "$pkg/" 2>/dev/null | sudo tar -x -C "$TARGET_DIR/" || true
    done

    # Install dependencies
    log "Installing dependencies..."
    cd "$TARGET_DIR/$MAIN_PKG"
    sudo -u $USER npm install --omit=dev 2>&1 | sudo tee -a "$LOG_FILE"

    # Restart PM2
    log "Restarting $PROCESS_NAME..."
    sudo -u $USER ${pm2Env}pm2 restart "$PROCESS_NAME" --no-color 2>&1 | sudo tee -a "$LOG_FILE"
    
    log "Current status:"
    sudo -u $USER ${pm2Env}pm2 list --no-color 2>&1 | sudo tee -a "$LOG_FILE"
done

log "=== Deployment completed ==="
`;
}

/**
 * Generate systemd-specific hook
 */
function generateSystemdHook(serviceName: string, config: ReturnType<typeof getServiceConfig>): string {
  const { server, packages, mainPackage, processName } = config;
  
  return `#!/bin/bash
# Post-receive hook for ${serviceName}
# Generated by git-deploy-cli
# Process Manager: systemd

set -e

SERVICE="${serviceName}"
TARGET_DIR="${server.targetDir}"
LOG_FILE="/var/log/deploy-${serviceName}.log"
PROCESS_NAME="${processName}"
PACKAGES=(${packages.map(p => `"${p}"`).join(' ')})
MAIN_PKG="${mainPackage}"
USER="${server.user || 'root'}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | sudo tee -a "$LOG_FILE"
}

log "=== Deployment started ==="

while read oldrev newrev refname; do
    BRANCH=$(echo "$refname" | sed 's|refs/heads/||')
    log "Received push to branch: $BRANCH"
    
    if [ "$BRANCH" != "main" ] && [ "$BRANCH" != "master" ]; then
        log "Ignoring non-main branch"
        continue
    fi

    # Extract packages using git archive
    for pkg in "\${PACKAGES[@]}"; do
        log "Extracting $pkg..."
        git archive "$BRANCH" "$pkg/" 2>/dev/null | sudo tar -x -C "$TARGET_DIR/" || true
    done

    # Set ownership
    sudo chown -R $USER:$USER "$TARGET_DIR"

    # Install dependencies
    log "Installing dependencies..."
    cd "$TARGET_DIR/$MAIN_PKG"
    sudo -u $USER npm install --omit=dev 2>&1 | sudo tee -a "$LOG_FILE"

    # Restart systemd service
    log "Restarting $PROCESS_NAME..."
    sudo systemctl restart "$PROCESS_NAME" 2>&1 | sudo tee -a "$LOG_FILE"
    
    log "Current status:"
    sudo systemctl status "$PROCESS_NAME" --no-pager 2>&1 | sudo tee -a "$LOG_FILE" || true
done

log "=== Deployment completed ==="
`;
}

/**
 * Init command - initialize bare repo, hook, and permissions on server
 */
export async function initCommand(serviceName: string, options: InitOptions = {}): Promise<void> {
  console.log(chalk.blue(`Initializing ${serviceName}...`));
  
  // Check root
  if (!isRoot()) {
    console.error(chalk.red('Error: init command requires root privileges. Run with sudo.'));
    process.exit(1);
  }
  
  const config = getServiceConfig(serviceName);
  const { server } = config;
  const groupName = server.group || `deploy-${serviceName}`;
  const logFile = `/var/log/deploy-${serviceName}.log`;
  
  // 1. Create group
  console.log(chalk.gray(`  Creating group ${groupName}...`));
  try {
    exec(`groupadd ${groupName}`, { silent: true });
  } catch {
    console.log(chalk.gray(`  Group ${groupName} already exists`));
  }
  
  // 2. Add users to group
  if (options.users) {
    const users = options.users.split(',').map(u => u.trim());
    for (const user of users) {
      console.log(chalk.gray(`  Adding user ${user} to group...`));
      try {
        exec(`usermod -aG ${groupName} ${user}`, { silent: true });
      } catch {
        console.log(chalk.yellow(`  Warning: Could not add user ${user}`));
      }
    }
  }
  
  // Add service user if configured
  if (server.user) {
    console.log(chalk.gray(`  Adding service user ${server.user} to group...`));
    try {
      exec(`usermod -aG ${groupName} ${server.user}`, { silent: true });
    } catch {
      console.log(chalk.yellow(`  Warning: Could not add user ${server.user}`));
    }
  }
  
  // 3. Create bare repo
  console.log(chalk.gray(`  Creating bare repo at ${server.bareRepo}...`));
  if (!exists(server.bareRepo)) {
    ensureDir(server.bareRepo);
    initBareRepo(server.bareRepo);
  } else {
    console.log(chalk.gray(`  Repo already exists`));
  }
  
  // 4. Create post-receive hook
  const hookPath = joinPath(server.bareRepo, 'hooks', 'post-receive');
  console.log(chalk.gray(`  Creating post-receive hook...`));
  const hookContent = generateHook(serviceName, config);
  writeFileSync(hookPath, hookContent);
  chmodSync(hookPath, 0o755);
  
  // 5. Create target directory
  console.log(chalk.gray(`  Creating target directory ${server.targetDir}...`));
  ensureDir(server.targetDir);
  if (server.user) {
    exec(`chown -R ${server.user}:${server.user} ${server.targetDir}`, { silent: true });
  }
  
  // 6. Create log file
  console.log(chalk.gray(`  Creating log file ${logFile}...`));
  exec(`touch ${logFile}`, { silent: true });
  exec(`chown root:${groupName} ${logFile}`, { silent: true });
  exec(`chmod 664 ${logFile}`, { silent: true });
  
  // 7. Set repo permissions
  exec(`chown -R root:${groupName} ${server.bareRepo}`, { silent: true });
  exec(`chmod -R g+rwX ${server.bareRepo}`, { silent: true });
  
  console.log(chalk.green(`✓ Initialized ${serviceName}`));
  console.log('');
  console.log(chalk.gray('Next steps:'));
  console.log(chalk.gray(`  1. On dev machine, add remote:`));
  console.log(chalk.white(`     git remote add deploy ssh://server${server.bareRepo}`));
  console.log(chalk.gray(`  2. Push to trigger deployment:`));
  console.log(chalk.white(`     git push deploy main`));
}
